### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by JeremyNeuhaus** [ChrisAdamsUK/OptionSetEditor#1]
Greetings i am getting an "Index was outside the bounds of the array" error when attempting to import my .csv

Attached is my .csv and the error message

Background
I am trying to import into a Global Option Set. 

[Import File.txt](https://github.com/ChrisAdamsUK/OptionSetEditor/files/2346617/Import.File.txt)
![optionsetxrmerror](https://user-images.githubusercontent.com/42948781/45002488-ac94ec00-af9c-11e8-84e4-041ffd39d5ae.jpg)

**Comment by ChrisAdamsUK** [comment]
Hi,

Sorry I have now fixed this. I was doing all my testing on my three language organization. And didn't retest the import when there wa sonly one language.

**Comment by zenecamickeyd** [comment]
I'm getting the same error message using v1.2.0 that I downloaded today.  Attached is the csv file I tried to import.  My organisation supports 6 languages.

[lead option sets TEXT VERSION.txt](https://github.com/ChrisAdamsUK/OptionSetEditor/files/2970823/lead.option.sets.TEXT.VERSION.txt)

**Comment by ChrisAdamsUK** [comment]
Hi,

The reason is that you do not have fields for the description. Add columns for descriptions and it will work. I will try to add some validation in for a future release. The easiest way is to export first then amend the exported file

Regards
Chris

**Comment by ChrisAdamsUK** [comment]
Hi,

The reason is that you do not have fields for the description. Add columns for descriptions and it will work. I will try to add some validation in for a future release. The easiest way is to export first then amend the exported file

Regards
Chris

**Comment by ChrisAdamsUK** [comment]
Hi,

Please find attached a corrected file with the description columns.

Regards
Chris

**Comment by zenecamickeyd** [comment]
Hi Chris,

This is now working after adding the Description columns back into the CSV file.  Thanks for your help.

Regards,
Michael
