### ISSUE TITLE
Accented characters are not exporting correctly

### ISSUE THREAD

**Issue by StillLearning1** [ChrisAdamsUK/OptionSetEditor#10]
I like your utility, however when I enter French language characters such as Éêé, they do not export correctly in the CSV file.

**Comment by ChrisAdamsUK** [comment]
Hi, I have checked this and it looks to be ok. If you are opening the file in Excel, you need to open it as unicode. please see the following link...

https://www.highviewapps.com/kb/special-characters-are-not-displaying-properly-when-i-open-my-shopify-csv-export-file-with-excel-or-another-spreadsheet-application-how-can-i-fix-this/#:~:text=Reviews-,Special%20characters%20are%20not%20displaying%20properly%20when%20I%20open%20my,Unicode%20(UTF%2D8).
