### ISSUE TITLE
Unable to export all fields listed

### ISSUE THREAD

**Issue by carterbeatsthedevil** [ChrisAdamsUK/OptionSetEditor#12]
Hi I have repeatedly tried to export all the picklist fields in a particular entity as shown in the tool but it only exports two or three fields and their values. Any ideas?

**Comment by ChrisAdamsUK** [comment]
Hi, You need to select all attributes to export them all. However I am just about to deploy V4 which changes the way it works so try again after this, hopefully it will be more intuitive.

Regards
Chris
