### ISSUE TITLE
Timeout on publish

### ISSUE THREAD

**Issue by guingui** [ChrisAdamsUK/OptionSetEditor#15]
![image](https://user-images.githubusercontent.com/71416515/104618594-e7be8400-565a-11eb-92e9-f3331745bc3b.png)
Want to publish about 200 updates
How is it possible to increase timeout value please ?

**Comment by ChrisAdamsUK** [comment]
Hi sorry, only just visited this page. 

The time out is fixed by Microsoft. However when it is only for a response from the publish command. If it takes longer, the publish should still be running in the background (i believe the message says this)
