### ISSUE TITLE
This plugin could not be installed into XrmToolBox

### ISSUE THREAD

**Issue by hcn0843** [ChrisAdamsUK/OptionSetEditor#2]
![xrmtollbox](https://user-images.githubusercontent.com/6252242/45994194-1b112980-c0c5-11e8-86e4-9e853f1bb12a.png)

**Comment by jromanjr** [comment]
Can someone help.

**Comment by Koenvdv** [comment]
I'm having the same issue. Once installed, the plugin asks to restart the application.
However, after restarting the application (and thus the XrmToolbox), the plugin doesn't show up in the list of installed plugins.
![2018-11-09 09_02_48-xrmtoolbox plugins store](https://user-images.githubusercontent.com/22298728/48250362-5c079800-e3fe-11e8-8d80-9f78aa50d04c.png)

![2018-11-09 09_03_07-xrmtoolbox for microsoft dynamics crm_365 ce v1 2018 10 29](https://user-images.githubusercontent.com/22298728/48250372-60cc4c00-e3fe-11e8-864f-e19ada537166.png)

**Comment by oteixeirafsu** [comment]
Can someone please help? I need this to work. I am experiencing the same issue.

**Comment by jhutjens** [comment]
Hi  @ChrisAdamsUK

Many users face the issue that we can not install your beautiful tool in the XRM toolbox. Are you able to fix this in a short notice? Much appreciated!

Kind regards,

Jeroen

**Comment by ChrisAdamsUK** [comment]
Hi,

I'm not sure how to fix this as installation from the toolbox is not covered b y my code. As far as I am aware it should install from the toolbox store. There is nothing in the plugin code regarding installation.

Regards
Chris
________________________________

**Comment by ChrisAdamsUK** [comment]
You can always download the plugin DLL directly then put it in you plugins folder bypassing the XRMtoolbox plugin store. :-)

**Comment by ChrisAdamsUK** [comment]
Hi Everyone, this is now fixed in V1.05 :-)

Chris
