### ISSUE TITLE
Installed version has a version numbering discrepency.

### ISSUE THREAD

**Issue by mscottsewell** [ChrisAdamsUK/OptionSetEditor#4]
Even after installing the latest version ("1.0.5") from the plug-in store, the "Installed Version" reports 1.0.0.0 - This causes it to continue to report that the installed version is not the 'latest version'

I've tried uninstalling/reinstalling - and of course - 'upgrading' the plugin from the plugin store - but it constantly reports that it's not the 'latest' version.

**Comment by JamesStuder** [comment]
Same as this closed ticket: https://github.com/ChrisAdamsUK/OptionSetEditor/issues/3

This has been reported by mulitple people now, but the developer keeps closing the ticket and makes it sound like this isn't an issue as "others" have been able to install it.

**Comment by ChrisAdamsUK** [comment]
Apologies, but we are not paid for creating these plugins so I don't always have the time to get round to fixing them between my paid work. The assembly file is showing the correct versions of the files. I have updated them again to see if it fixes it. I have also contact the XRM toolbox team to see why it could be happening. Please try again on V1.2

**Comment by JamesStuder** [comment]
Yes the new version number installed and removed from the store after install.

**Comment by ChrisAdamsUK** [comment]
Thanks,

I tried it myself too and it seemed to work 😊

Chris
