### ISSUE TITLE
Pressing the move up/down buttons do not appear to do anything

### ISSUE THREAD

**Issue by samlh** [ChrisAdamsUK/OptionSetEditor#5]
Selecting an option set value and pressing the move up buttons does not do anything.

Expected:
The value should swap places with the previous value.

Actual:
The selected row highlight moves to the previous value, but the value itself does not move.

This is using option set editor version 1.2.0.0 from the toolbox plugin manager.

**Comment by ChrisAdamsUK** [comment]
Hi,
This has been fixed in V3 :-)
