### ISSUE TITLE
Ability to edit Global option sets

### ISSUE THREAD

**Issue by fayezm** [ChrisAdamsUK/OptionSetEditor#6]
Hi,
Thanks for this plugin - would it be possible to modify global option sets using this tool?

**Comment by ChrisAdamsUK** [comment]
Yes, it already allows modification of global optionsets. They are marked with an asterisk when they are global 😁

**Comment by ChrisAdamsUK** [comment]
Yes, it already allows modification of global optionsets. They are marked with an asterisk when they are global 😁
