### ISSUE TITLE
Edit Optionsets from Managed Solutions marked as non customizable

### ISSUE THREAD

**Issue by nickbrandl** [ChrisAdamsUK/OptionSetEditor#7]
If an entity has been marked as non-customizable, this plug-in does not display the entity in the entity list. This is fine only if the component is in managed state, otherwise, you should allow to customize it. This is the case of components in the development enviroment.

**Comment by ChrisAdamsUK** [comment]
Thanks, apologies for not getting time to fix this. I've included it in the latest release :-)
