### ISSUE TITLE
MultiSelect Option Set Support

### ISSUE THREAD

**Issue by dtedwards** [ChrisAdamsUK/OptionSetEditor#9]
I have a MultiSelect Option Set that uses a Global Option set and I am not able to see that in XRMToolbox in the Option Set Editor tool.

If I add a new field to the entity that is just a simple Option Set and not MultiSelect, then I am able to see it in the tool.

**Comment by ChrisAdamsUK** [comment]
Hi, I have tested this and cannot replicate it. Van you please confirm you are using the latest version of the plugin?

regards
Chris
